#!/bin/bash

estaNoIntervalo() {
	if [ $numero -lt 0 ] || [ $numero -gt 10 ]; then
		echo 'Numero fora do intervalo';
		exit;
	fi
}

existePastaLog() {
	if [ -d log ]; then
		echo Deleting the log folder
    	rm -rf log
	fi
}

echo -n "Digite um número de 0 até 10: "
read numero

existePastaLog

mkdir log
echo Digitou inicialmente $numero >> log/file

while [[ $numero != '5' ]]
do
	# chama função que verifica se o numero é válido
	estaNoIntervalo

	echo Numero $numero não está certo
	read numero
	echo Tentou $numero >> log/file
done

rm -rf log